

const ALERT = 'ALERT';

const REFETCH_CHATS = 'REFETCH_CHATS';

const NEW_ATTACHMET = "NEW_ATTACHMET";

const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";

const NEW_MESSAGE = "NEW_MESSAGE"
const START_TYPING = "START_TYPING"
const STOP_TYPING = "STOP_TYPING"
const CHAT_JOINED = "CHAT_JOINED"
const CHAT_EXITED = "CHAT_EXITED"
const ONLINE_USERS = "ONLINE_USERS"

export {NEW_MESSAGE_ALERT,ALERT,REFETCH_CHATS,NEW_ATTACHMET,NEW_MESSAGE,NEW_REQUEST,START_TYPING,STOP_TYPING,CHAT_EXITED,CHAT_JOINED,ONLINE_USERS}